[build]
  command = "npm run build"
  publish = "out"

[context.production.environment]
  NODE_VERSION = "20"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
